# Chat Application
version: "3"

services:
  auth:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    #   args: 
    #   - PORT=3000
    #   - MONGODB_CONNECTION_STRING="mongodb://mongodb:27017/chat"
    #   - SEQ_SERVER="http://seq:5341"
    ports:
      - "3002:3000"
    networks:
      - chat-network
    container_name: auth-app
    environment:
      - PORT=3000
      - MONGODB_CONNECTION_STRING="mongodb://mongodb:27017/chat"
      - SEQ_SERVER="http://seq:5341"

  chat:
    build:
      context: ./services/chat-service
      dockerfile: Dockerfile
      args: 
        - PORT=3000
        - MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING}
        - SEQ_SERVER=${SEQ_SERVER}
    ports:
      - "3001:3000"
    networks:
      - chat-network
    container_name: chat-app
    environment:
      - PORT=${PORT}
      - MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING}
      - SEQ_SERVER=${SEQ_SERVER}
  
  database:
    image: 'mongo'
    container_name: 'mongodb'
    volumes:
      - /data/db
    ports:
      - '27017-27019:27017-27019'
    networks:
      - chat-network
  
  logging:
    image: 'datalust/seq'
    container_name: seq
    volumes:
      - ./volumes/seq:/data
    ports:
      - 8080:80
      - 5341:5341
    environment:
      - ACCEPT_EULA=Y
    networks:
      - chat-network

networks:
  chat-network: